# Generated by Django 4.1.5 on 2023-01-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='image',
            field=models.ImageField(upload_to='\\images'),
        ),
    ]
