# Generated by Django 4.1.5 on 2023-02-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_react_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='image',
        ),
    ]
