# Generated by Django 4.1.5 on 2023-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_react_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='year',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Freshman', max_length=9),
        ),
    ]
