# Generated by Django 4.1.5 on 2023-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_react_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='react',
            name='year',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate Student', 'Graduate')], default='Freshman', max_length=16),
        ),
    ]
