# Generated by Django 4.1.5 on 2023-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='react',
            name='email',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.RemoveField(
            model_name='react',
            name='year',
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='blankField',
            field=models.CharField(default='j', max_length=1),
            preserve_default=False,
        ),
    ]
