# Generated by Django 4.1.5 on 2023-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_partnerusernme_profile_partnerusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isProfileComplete',
            field=models.BooleanField(default=False),
        ),
    ]
