# Generated by Django 4.1.5 on 2023-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_isprofilecomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isMatchStarted',
            field=models.BooleanField(default=False),
        ),
    ]
