# Generated by Django 4.1.5 on 2023-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_ismatchstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isMatched',
            field=models.BooleanField(default=False),
        ),
    ]
