# Generated by Django 4.1.3 on 2023-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_ismatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/Users/kaiwang/Desktop/coffeechat/sp23-blue-coffeechat/env/coffeechat/media/profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
