# Generated by Django 4.1.5 on 2023-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_formatching',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partnerUsername',
            field=models.CharField(default='', max_length=100),
        ),
    ]
