# Generated by Django 4.1.5 on 2023-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_username_formatching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='partnerUsername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username_formatching',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
