# Generated by Django 4.1.5 on 2023-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_partnerusername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='partnerUsername',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='username_formatching',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
